apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-sivtsov-certificate
spec:
  dnsNames:
  - 'sivtsov.dacdevops.ru'
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: sivtsov-cert