apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gleb-sampleapp
 
resources:
  - ../../base
  - certificate.yaml
  - namespace.yaml

images:
  - name:  ghost19/sampleapp
  - name: nginx
    newName: nginx
    newTag: 1.23.2-alpine